# Generated by Django 3.2.5 on 2021-08-24 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MappingUrl',
            fields=[
                ('created', models.DateTimeField(auto_now=True)),
                ('originUrl', models.URLField(primary_key=True, serialize=False)),
                ('shortenString', models.CharField(max_length=8)),
            ],
        ),
    ]
